[build.processing]
  skip_processing = false

[build.processing.html]
  minify = true

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.images]
  compress = true


[[redirects]]
  from = "https://toheeb.com"
  to = "https://blog.toheeb.com"
  status = 302
  force = true

[[redirects]]
  from = "https://www.toheeb.com"
  to = "https://blog.toheeb.com"
  status = 302
  force = true